services:
  django:
    image: extensions_backend:latest
    container_name: extensions-backend
    build:
      context: ..
      dockerfile: Dockerfile-prod
    # network_mode: host
    ports:
      - '8005:8005'
    command:  >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8005"
    env_file:
      - ../.env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: extensions_database
    restart: always
    environment:
      - POSTGRES_USER=extension
      - POSTGRES_PASSWORD=ext2026
      - POSTGRES_DB=extensions_db
    ports:
      - '5433:5432'
 